### PR TITLE
wideq: Implement AC

### PR DESCRIPTION
**Pull request by d3m3vilurr**
I dont's make HA part yet(sorry I'm new of the ha)

this patch add to support AC control (related #37) and I'm only tested my system AC(model: `CST_570004_WW`)

properties:
- is_on: return the device on/off state
- current_temp
- target_temp
- current_humidity: a value seems `*10`
- wind_strength [= enum]: current strength & set new value, enum should be part of `SUPPORT_AC_WIND_STRENGTH`
- operation [= bool]: current state & turn on/off device
- operation_mode [= enum]: current wind type & set new value, enum should be part of `SUPPORT_AC_OPERATION_MODE`
- autodry_mode [= bool]: current mode & turn on/off mode
- airclean_mode [= bool]: current mode & turn on/off mode
- filter_remain: return the percent of the AC filter
- wind_up_down [= bool]: current state & turn on/off up/down wind mode
- wind_left_right [= bool]: current state & turn on/off left/right wind mode
- wind_vstep [= int]: current value & change up/down wind degrees, value should be 1-6

a control action uses @stefxx 's information of #47 & @brunostavares 's implementation.

### CODE REVIEW

**Comment by KTibow** [comment]
Wow. 👏 That's a lot. Try to have a version ready without commented out code, when it's time for this to be merged.

**Comment by d3m3vilurr** [comment]
removed some TODO comments; I think it is unimportant.
maybe a project should make the guide about command like syssi/xiaomi_airpurifier
and add `GuideType` for next work(air purifier)

**Comment by ollo69** [comment]
Thanks for your job, I will take a look tp this PR this w.e.

**Comment by ollo69** [comment]
@d3m3vilurr,

this is a big change that also will require additional work to have climate device available for integration.
If you agree I can create a new dedicated branch and you can push your PRs to this branch, so that we can handle multiple PRs without having the risk to break current implementation in master branch. We will finally merge to master when everything is ready.

**Comment by d3m3vilurr** [comment]
@ollo69 yep. that sounds good to me. :)

**Comment by ollo69** [comment]
Created new branch: https://github.com/ollo69/ha-smartthinq-sensors/tree/AC-Implementation
Please create new PR pushing your change to this branch

**Comment by d3m3vilurr** [comment]
rebased & changed base branch

**Comment by beped** [comment]
Any progress here? Any forecast?

**Comment by d3m3vilurr** [comment]
I couldn't start to make the HA components yet. but if someone make the component, it probably work.
next step i'll invest air purifier. (actually i also have plan to invest styler. but it seems already added at ce98e896731)

**Comment by ollo69** [comment]
I start merging this and  than I will rebase with my last changes, than I will try to manage HA component as next step.
If you have some update don't hesitate to create new PR.

**Pull request merged**
