### PR TITLE
Improved portuguese translation

### PR DESCRIPTION
**Pull request by fnasciment0**
Improved portuguese translation file.

### CODE REVIEW

**Review by xilopaint — COMMENTED** [review]
The word "inserir" is misspelled.

**Comment by xilopaint** [comment]
Also, the English version uses the imperative form. Maybe you should write "Insira informações de acesso" instead of "Inserir informações de acesso", "Não use" instead of "Não usar", "Use o método de autenticação"  instead of "Usar método de autenticação", "Compartilhe a conexão HTTP" instead of "Partilhar ligação HTTP", "Force o uso do protocolo" instead of "Forçar o uso do protocolo", "Use o URL no primeiro campo" instead of "Usar o URL no primeiro campo".

I'm not from Portugal but it would be the correct approach in Brazilian Portuguese.

**Comment by fnasciment0** [comment]
In Portuguese it is also common to use the infinitive form, both approaches are correct. 
Anyway, I'll change it following your recommendations.

**Comment by xilopaint** [comment]
I understand that the infinitive form does exist in Portuguese. I'm just pointing out that the English translation uses the imperative form, and it's usually better to follow that pattern.

**Comment by ollo69** [comment]
Thanks👍

**Pull request merged**
