### PR TITLE
Add basic support for dehumidifiers

### PR DESCRIPTION
**Pull request by rain931215**
Only support power toggle now.
I think we should implement this as a fan entity in future so we can change working mode in HA.

### CODE REVIEW

**Comment by mountain0320** [comment]
How do you currently use the dehumidifier?

**Comment by OTZro** [comment]
+1
I need this. Please take a look this feature. I can do help if need.

**Comment by JvdMaat** [comment]
I have an LG dehumidifier in my ThinQ app, but it is not showing in HA with this integration. Is there basic support yet?

**Comment by ollo69** [comment]
On past days I worked to convert integration to full async. 
This is my next step, I need to find available times for this. I hope I can start working on this in a couple of weeks.

**Comment by ollo69** [comment]
I close this old PR, dehumidifier support is released with last version.

**Comment by JvdMaat** [comment]
Awesome, thanks!
image

**Pull request closed without merging**
