### PR TITLE
Unit tests for wideq

### PR DESCRIPTION
**Pull request by thomaskistler**
This commit adds unit tests for wideq. Run the tests from within the smartthinq_sensors directory using `python -m unittest -v`

### CODE REVIEW

**Comment by KTibow** [comment]
Could you consider trying to add CI for the unit tests as well? If you find it too complicated, I can do it.

**Comment by thomaskistler** [comment]
Why don't you take a stab at it. I'm a bit short on time for the next few weeks.

**Comment by KTibow** [comment]
How do you run these tests? Do you need any libraries to be downloaded first?

**Comment by ollo69** [comment]
It could be possible run this unit test inside the dev container that I just added to the repo? Can someone review this tests based on current development status?

**Comment by thomaskistler** [comment]
Closing this PR. This PR is out of date and someone should write proper unit tests for wideq that uses mocks for client responses.

**Pull request closed without merging**
