### PR TITLE
Add airmon as a switch?

### PR DESCRIPTION
**Pull request by skinkie**
I have tried to implement airmon _always on_ as a switch. But for some reason the switch does not appear under the controls, neither do I see any errors on why it is not enumerated. Any clues?

### CODE REVIEW

**Comment by ollo69** [comment]
@skinkie ,

can you take a look to last release in master branch and test with your devices? 
I added a control to not return PMs values if air sensors are not active, status that I suppose is provided by `airState.quality.sensorMon`, but I'm not sure that this property is really updated based on airmon always on status.

**Comment by skinkie** [comment]
@ollo69 is there a smart way to run master without just copying over the files?

**Comment by ollo69** [comment]
If you are using HACS you can install integration again and select the branch `master`, it will replace the file for you. Later you can move back to last release.

**Comment by skinkie** [comment]
To answer your question, yes it works. When switched off, it is unavailable, when turned on it reports its status.
image

In my ideal world I would like to have constant monitoring (iff the device would support it).

**Comment by ollo69** [comment]
> In my ideal world I would like to have constant monitoring (iff the device would support it).

But this is not an existing option? I was supposing that this option exist via ThinQ app or remote, if it doesn't it is enough check if device is on. What are values returned in LG App when device is off?

**Comment by skinkie** [comment]
I thought I understood from the debug output, that setting "airState.quality.airMon = 1" would give an _always on monitoring_. This is **not** something that I have found in the ThinQ app.

**Comment by ollo69** [comment]
If the option is not available in LG app, probably is not an available function, or at least not supported by your devices. 
I ask again, what are the PMs values reported by LG app when device is off?

**Comment by skinkie** [comment]
> If the option is not available in LG app, probably is not an available function, or at least not supported by your devices.

My question for you: would it be possible to send this 'command' this attribute to the device to test it?

>  I ask again, what are the PMs values reported by LG app when device is off?

I have no clue, I removed the 120MB of bloatware from my phone, once you resolved the authentication issues.

**Comment by ollo69** [comment]
> My question for you: would it be possible to send this 'command' this attribute to the device to test it?

Theoretically, but I have no idea of what should be the correct command format. This integration is mostly based on command sent by LG app, if this is not available is not possible to determinate the correct format (if exist)


> I have no clue, I removed the 120MB of bloatware from my phone, once you resolved the authentication issues.

Ok, but is correct assume that when AC is off PMs sensor should not be considered?

**Comment by skinkie** [comment]
> > I have no clue, I removed the 120MB of bloatware from my phone, once you resolved the authentication issues.
> 
> Ok, but is correct assume that when AC is off PMs sensor should not be considered?

I think this is the behavior described and observed, and I honestly wonder how there could be airflow through the sensor without any ventilator operating.

But considering below, how do you typically distinguish between a property that can be set, versus a property that can only be read? Obviously I wounder understand that when this is more like an informative thing "this sensor only works when operating" it would also perfectly make sense.

```
      "airState.quality.airMon": {
        "data_type": "enum",
        "default": "0",
        "value_mapping": {
          "0": "@AP_SETTING_SENSORMON_OPERATIONING_W",
          "1": "@AP_SETTING_SENSORMON_ALWAYS_W"
        }
      },
```

**Comment by ollo69** [comment]
There are no rule to know if can be written or not, but for sure this property cannot be read from your device. If you open device diagnostic and go to the `device_info` section you can find inside the `snapshot` that contain exposed values.

**Comment by skinkie** [comment]
Agreed. Then lets close this :-)
```
            "snapshot": {
              "airState.windStrength": 4.0,
              "airState.wMode.lowHeating": 0.0,
              "airState.diagCode": 0.0,
              "airState.lightingState.displayControl": 1.0,
              "airState.wDir.hStep": 35.0,
              "mid": 4119703126.0,
              "airState.energy.onCurrent": 50.0,
              "airState.wMode.airClean": 0.0,
              "airState.quality.sensorMon": 0.0,
              "airState.miscFuncState.antiBugs": 0.0,
              "airState.tempState.target": 22.0,
              "airState.miscFuncState.autoDryRemainTime": 0.0,
              "airState.operation": 0.0,
              "airState.wMode.jet": 0.0,
              "airState.wDir.vStep": 6.0,
              "timestamp": 1698190826281.0,
              "airState.powerSave.basic": 0.0,
              "airState.quality.PM10": 8.0,
              "fwUpgradeInfo": {
                "upgSched": {
                  "upgUtc": "0",
                  "cmd": "none"
                }
              },
              "static": {
                "deviceType": "401",
                "countryCode": "NL"
              },
              "airState.miscFuncState.Uvnano": 1.0,
              "airState.quality.overall": 0.0,
              "airState.tempState.current": 18.0,
              "airState.miscFuncState.extraOp": 0.0,
              "airState.reservation.sleepTime": 0.0,
              "airState.miscFuncState.autoDry": 0.0,
              "airState.reservation.targetTimeToStart": 0.0,
              "meta": {
                "allDeviceInfoUpdate": false,
                "messageId": "blRO-wRBR-CHo66M9mItkQ"
              },
              "airState.quality.PM1": 8.0,
              "airState.wMode.smartCare": 0.0,
              "airState.quality.PM2": 8.0,
              "online": true,
              "airState.opMode": 4.0,
              "airState.reservation.targetTimeToStop": 0.0,
              "airState.filterMngStates.maxTime": 0.0,
              "airState.filterMngStates.useTime": 0.0
            },
```

**Comment by skinkie** [comment]
Agreed. Then lets close this :-)
```
            "snapshot": {
              "airState.windStrength": 4.0,
              "airState.wMode.lowHeating": 0.0,
              "airState.diagCode": 0.0,
              "airState.lightingState.displayControl": 1.0,
              "airState.wDir.hStep": 35.0,
              "mid": 4119703126.0,
              "airState.energy.onCurrent": 50.0,
              "airState.wMode.airClean": 0.0,
              "airState.quality.sensorMon": 0.0,
              "airState.miscFuncState.antiBugs": 0.0,
              "airState.tempState.target": 22.0,
              "airState.miscFuncState.autoDryRemainTime": 0.0,
              "airState.operation": 0.0,
              "airState.wMode.jet": 0.0,
              "airState.wDir.vStep": 6.0,
              "timestamp": 1698190826281.0,
              "airState.powerSave.basic": 0.0,
              "airState.quality.PM10": 8.0,
              "fwUpgradeInfo": {
                "upgSched": {
                  "upgUtc": "0",
                  "cmd": "none"
                }
              },
              "static": {
                "deviceType": "401",
                "countryCode": "NL"
              },
              "airState.miscFuncState.Uvnano": 1.0,
              "airState.quality.overall": 0.0,
              "airState.tempState.current": 18.0,
              "airState.miscFuncState.extraOp": 0.0,
              "airState.reservation.sleepTime": 0.0,
              "airState.miscFuncState.autoDry": 0.0,
              "airState.reservation.targetTimeToStart": 0.0,
              "meta": {
                "allDeviceInfoUpdate": false,
                "messageId": "blRO-wRBR-CHo66M9mItkQ"
              },
              "airState.quality.PM1": 8.0,
              "airState.wMode.smartCare": 0.0,
              "airState.quality.PM2": 8.0,
              "online": true,
              "airState.opMode": 4.0,
              "airState.reservation.targetTimeToStop": 0.0,
              "airState.filterMngStates.maxTime": 0.0,
              "airState.filterMngStates.useTime": 0.0
            },
```

**Pull request closed without merging**
